
create table if not exists users (
    id int generated by default as identity primary key,
    email varchar(50),
    login varchar(200),
    name varchar(50),
    birthday timestamp
);

create table if not exists mpa (
    id int generated by default as identity primary key,
    name varchar(50)
);

create table if not exists genres (
    id int generated by default as identity primary key,
    name varchar(50)
);

create table if not exists films (
    id int generated by default as identity primary key,
    name varchar(50),
    description varchar(200),
    release_date timestamp,
    duration int,
    rate int,
    mpa_id int,
    CONSTRAINT fk_films_mpa
        FOREIGN KEY (mpa_id)
            REFERENCES mpa (id)
);

create table if not exists films_genres (
    film_id int REFERENCES films(id),
    genre_id int REFERENCES genres(id)
);

create table if not exists friends (
    user_id int REFERENCES users(id),
    friend_id int REFERENCES users(id)
);

create table if not exists likes (
    film_id int REFERENCES films(id),
    user_id int REFERENCES users(id)
);

create table if not exists Reviews
(
    id int generated by default as identity primary key,
    content varchar not null ,
    is_positive boolean not null ,
    rate integer default 0,
    film_id integer references films(id) on delete cascade ,
    user_id integer references users(id) on delete cascade
);

create table if not exists Reviews_likes
(
    review_id integer references Reviews(id) on delete cascade ,
    user_id integer references users (id) on delete cascade,
    is_useful boolean not null
);


INSERT INTO genres (name)
VALUES ('Комедия'), ('Драма'), ('Мультфильм'), ('Триллер'), ('Документальный'), ('Боевик');
INSERT INTO mpa (name)
VALUES ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17');


-- INSERT INTO USERS
-- (EMAIL, LOGIN, NAME, BIRTHDAY)
-- VALUES ('test@test.com', 'test1', 'user1', '1999-11-5'),
--        ('test@test.com', 'test2', 'user2', '1988-11-5'),
--        ('test@test.com', 'test3', 'user3', '1977-11-5');
--
-- INSERT INTO FILMS
-- (NAME, DESCRIPTION, DURATION, RELEASE_DATE, MPA_ID)
-- VALUES ('test-film', 'about test', 18, '1993-1-11', 5),
--        ('test-film2', 'about test', 18, '1994-2-22', 5);

